# support method:
# disable: disable this protocol
# nvram: try get ip by nvram, only work on ea6500v2, other platform is not tested yet
# lanip: try get ip by lan ip address
# network_api: get ip from a api
# static: set a static ip address
# fix_suffix: set a ip address with a fixed suffix
# more detail in readme.md
get_ipv4_method:
  - method: network_api
    api: http://v4.ip.zxinc.org/getip
    # regex:
    # custom_head: 
      # xxx: yyy
get_ipv6_method:
  # - method: lanip
  #   networkcard: en0
  - method: fix_suffix
    suffix: ::a:b:c:d
    prefix_method: 
      method: static
      address: 1:2:3:4::5
    prefix_length: 64
  
# interval is measured in seconds
# 0 means run once and quit
refresh_interval: 60
# dnspod token
token: xxx,yyy
basedomain: example.com
subdomain: www