# support method:
# disable: not enable this protocol
# wanip: try get ip by wan ip, only work on ea6500v2, other platform is not tested yet
# lanip: try get ip by lan ip address
# ip.cip.cc: get ip from ip.cip.cc, ipv4 only
get_ipv4_method:
  - method: network_api
    api: http://v4.ip.zxinc.org/getip
    # regex:
    # custom_head: 
      # xxx: yyy
  - method: wanip
get_ipv6_method:
  # - method: lanip
  #   networkcard: en0
  - method: fix_suffix
    suffix: ::a:b:c:d
    prefix_method: 
      method: static
      address: 1:2:3:4::5
    prefix_length: 64
  
# interval is measured in seconds
# 0 means run once and quit
refresh_interval: 60
# dnspod token
token: xxx,yyy
basedomain: example.com
subdomain: www